apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: shopcloud
spec:
  template:
    spec:
      containers:
        - name: catalog
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/shopcloud/catalog:prod-latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: shopcloud
spec:
  template:
    spec:
      containers:
        - name: cart
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/shopcloud/cart:prod-latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: shopcloud
spec:
  template:
    spec:
      containers:
        - name: checkout
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/shopcloud/checkout:prod-latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: shopcloud
spec:
  template:
    spec:
      containers:
        - name: auth
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/shopcloud/auth:prod-latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: shopcloud
spec:
  template:
    spec:
      containers:
        - name: admin
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/shopcloud/admin:prod-latest
