apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopcloud-dr-irsa-catalog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopcloud-dr-irsa-cart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopcloud-dr-irsa-checkout
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopcloud-dr-irsa-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopcloud-dr-irsa-admin
