# helm repo add external-secrets https://charts.external-secrets.io
# helm upgrade --install external-secrets external-secrets/external-secrets \
#   -n external-secrets --create-namespace -f external-secrets.yaml
serviceAccount:
  create: true
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/shopcloud-primary-irsa-external-secrets
webhook:
  serviceAccount:
    create: true
certController:
  serviceAccount:
    create: true
resources:
  requests: { cpu: 20m, memory: 64Mi }
  limits:   { cpu: 100m, memory: 128Mi }
