apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopcloud

resources:
  - ../../base/namespace.yaml
  - ../../base/default-deny.yaml
  - ../../base/external-secrets.yaml
  - ../../base/catalog/catalog.yaml
  - ../../base/cart/cart.yaml
  - ../../base/checkout/checkout.yaml
  - ../../base/auth/auth.yaml
  - ../../base/admin/admin.yaml
  - ../../base/frontend/frontend.yaml
  - ../../base/ingress/public.yaml
  - ../../base/ingress/admin.yaml
  - ../../base/keda/checkout-sqs-scaler.yaml

commonLabels:
  region: us-east-1
  environment: production
