apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  region: us-east-1
  environment: production

patches:
  - path: patches/primary-secrets.yaml
  - path: patches/primary-images.yaml
