apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  region: us-east-1
  environment: development

patches:
  - path: patches/dev-scale.yaml
  - path: patches/dev-service-accounts.yaml
  - path: patches/dev-images.yaml
