apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopcloud-public
  namespace: shopcloud
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/group.name: shopcloud-public
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/catalog
            pathType: Prefix
            backend: { service: { name: catalog,  port: { number: 8080 } } }
          - path: /api/cart
            pathType: Prefix
            backend: { service: { name: cart,     port: { number: 8080 } } }
          - path: /api/checkout
            pathType: Prefix
            backend: { service: { name: checkout, port: { number: 8080 } } }
          - path: /api/auth
            pathType: Prefix
            backend: { service: { name: auth,     port: { number: 8080 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: catalog, port: { number: 8080 } } }
