apiVersion: v1
kind: ConfigMap
metadata:
  name: shopcloud-config
  namespace: shopcloud
data:
  DB_HOST: "placeholder"
  DB_PORT: "5432"
  DB_NAME: "shopcloud"
  REDIS_HOST: "placeholder"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
