apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secrets.yaml
  - catalog/catalog.yaml
  - cart/cart.yaml
  - checkout/checkout.yaml
  - auth/auth.yaml
  - admin/admin.yaml
  - ingress/public.yaml
  - ingress/admin.yaml
  - monitoring/barebones.yaml
  - monitoring/dashboard.yaml
